application: wellesley-daily-dish
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /tasks/send_alerts
  script: main.application
  login: admin

- url: /_ah/bounce
  script: main.application
  login: admin

- url: /unsubscribe/.*
  script: main.application
  secure: always

- url: /.*
  script: main.application
  secure: always


libraries:
- name: webapp2
  version: 2.5.2

- name: jinja2
  version: 2.6


inbound_services:
- mail_bounce