application: wellesley-fresher
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /tasks/send_alerts
  script: main.application
  login: admin

- url: /.*
  script: main.application


libraries:
- name: webapp2
  version: 2.5.2

- name: jinja2
  version: 2.6